// src/engine/formulas/chemistry.js
// Chemistry formulas — moles, concentration, gas laws, acids/bases, thermo, kinetics.

const fmt = (n) => {
  if (!Number.isFinite(n)) return 'Invalid';
  if (n === 0) return '0';
  const abs = Math.abs(n);
  if (abs < 1e-6 || abs >= 1e10) {
    return n.toExponential(4).replace(/\.?0+e/, 'e');
  }
  return Number(n.toPrecision(8)).toString();
};

const pct = (n) => `${fmt(n)} %`;

export const CHEMISTRY_FORMULAS = [
  // ─── Moles & Stoichiometry ────────────────────────────────────────────
  { id: 'moles-from-mass', category: 'chemistry', name: 'Moles from Mass',
    formula: 'n = m / M', description: 'Moles from mass and molar mass',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (g)', default: '36' },
      { key: 'M', symbol: 'M', label: 'Molar mass (g/mol)', default: '18' },
    ],
    compute: ({ m, M }) => M === 0 ? 'Division by zero' : fmt(m / M),
  },
  { id: 'mass-from-moles', category: 'chemistry', name: 'Mass from Moles',
    formula: 'm = n × M', description: 'Mass from moles',
    inputs: [
      { key: 'n', symbol: 'n', label: 'Moles', default: '2' },
      { key: 'M', symbol: 'M', label: 'Molar mass (g/mol)', default: '18' },
    ],
    compute: ({ n, M }) => fmt(n * M),
  },
  { id: 'particles-from-moles', category: 'chemistry', name: 'Particles from Moles',
    formula: 'N = n × N_A', description: "Avogadro's number",
    inputs: [{ key: 'n', symbol: 'n', label: 'Moles', default: '1' }],
    compute: ({ n }) => fmt(n * 6.02214076e23),
  },
  { id: 'moles-from-particles', category: 'chemistry', name: 'Moles from Particles',
    formula: 'n = N / N_A', description: 'Moles from particle count',
    inputs: [{ key: 'N', symbol: 'N', label: 'Particles', default: '6.022e23' }],
    compute: ({ N }) => fmt(N / 6.02214076e23),
  },
  { id: 'molar-mass', category: 'chemistry', name: 'Molar Mass',
    formula: 'M = m / n', description: 'Molar mass',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (g)', default: '36' },
      { key: 'n', symbol: 'n', label: 'Moles', default: '2' },
    ],
    compute: ({ m, n }) => n === 0 ? 'Division by zero' : fmt(m / n),
  },

  // ─── Concentration ────────────────────────────────────────────────────
  { id: 'molarity', category: 'chemistry', name: 'Molarity',
    formula: 'M = n / V', description: 'Concentration (mol/L)',
    inputs: [
      { key: 'n', symbol: 'n', label: 'Moles (mol)', default: '0.5' },
      { key: 'V', symbol: 'V', label: 'Volume (L)', default: '2' },
    ],
    compute: ({ n, V }) => V === 0 ? 'Division by zero' : fmt(n / V),
  },
  { id: 'moles-from-molarity', category: 'chemistry', name: 'Moles from Molarity',
    formula: 'n = M × V', description: 'Moles from molarity',
    inputs: [
      { key: 'M', symbol: 'M', label: 'Molarity (M)', default: '0.5' },
      { key: 'V', symbol: 'V', label: 'Volume (L)', default: '2' },
    ],
    compute: ({ M, V }) => fmt(M * V),
  },
  { id: 'dilution', category: 'chemistry', name: 'Dilution',
    formula: 'C₁V₁ = C₂V₂', description: 'Solve for C₂',
    inputs: [
      { key: 'C1', symbol: 'C₁', label: 'Initial conc', default: '2' },
      { key: 'V1', symbol: 'V₁', label: 'Initial vol (L)', default: '0.5' },
      { key: 'V2', symbol: 'V₂', label: 'Final vol (L)', default: '2' },
    ],
    compute: ({ C1, V1, V2 }) => V2 === 0 ? 'Division by zero' : fmt((C1 * V1) / V2),
  },
  { id: 'molality', category: 'chemistry', name: 'Molality',
    formula: 'm = n / kg_solvent', description: 'Moles per kg solvent',
    inputs: [
      { key: 'n',  symbol: 'n',  label: 'Moles solute', default: '0.5' },
      { key: 'kg', symbol: 'kg', label: 'kg solvent', default: '1' },
    ],
    compute: ({ n, kg }) => kg === 0 ? 'Division by zero' : fmt(n / kg),
  },
  { id: 'mass-percent', category: 'chemistry', name: 'Mass Percent',
    formula: '% = (m_solute/m_solution)×100', description: 'Mass percent',
    inputs: [
      { key: 'ms',  symbol: 'm_solute',   label: 'Solute mass (g)', default: '10' },
      { key: 'msol', symbol: 'm_solution', label: 'Solution mass (g)', default: '100' },
    ],
    compute: ({ ms, msol }) => msol === 0 ? 'Division by zero' : pct((ms / msol) * 100),
  },
  { id: 'mole-fraction', category: 'chemistry', name: 'Mole Fraction',
    formula: 'x_A = n_A / n_total', description: 'Mole fraction',
    inputs: [
      { key: 'nA',   symbol: 'n_A',     label: 'Moles A', default: '2' },
      { key: 'ntot', symbol: 'n_total', label: 'Total moles', default: '5' },
    ],
    compute: ({ nA, ntot }) => ntot === 0 ? 'Division by zero' : fmt(nA / ntot),
  },
  { id: 'normality', category: 'chemistry', name: 'Normality',
    formula: 'N = M × n_eq', description: 'Normality',
    inputs: [
      { key: 'M', symbol: 'M', label: 'Molarity', default: '0.5' },
      { key: 'n', symbol: 'n_eq', label: 'Equivalents', default: '2' },
    ],
    compute: ({ M, n }) => fmt(M * n),
  },
  { id: 'dilution-factor', category: 'chemistry', name: 'Dilution Factor',
    formula: 'DF = V_final / V_aliquot', description: 'Dilution ratio',
    inputs: [
      { key: 'vf', symbol: 'V_final',  label: 'Final volume', default: '100' },
      { key: 'va', symbol: 'V_aliquot', label: 'Aliquot', default: '10' },
    ],
    compute: ({ vf, va }) => va === 0 ? 'Division by zero' : fmt(vf / va),
  },
  { id: 'molar-volume', category: 'chemistry', name: 'Molar Volume',
    formula: 'Vm = V / n', description: 'Volume per mole',
    inputs: [
      { key: 'V', symbol: 'V', label: 'Volume (L)', default: '22.4' },
      { key: 'n', symbol: 'n', label: 'Moles',      default: '1' },
    ],
    compute: ({ V, n }) => n === 0 ? 'Division by zero' : fmt(V / n),
  },

  // ─── Gas Laws ─────────────────────────────────────────────────────────
  { id: 'ideal-gas-v', category: 'chemistry', name: 'Ideal Gas (V)',
    formula: 'V = nRT/P', description: 'Volume of ideal gas',
    inputs: [
      { key: 'n', symbol: 'n', label: 'Moles', default: '1' },
      { key: 'T', symbol: 'T', label: 'Temperature (K)', default: '273.15' },
      { key: 'P', symbol: 'P', label: 'Pressure (atm)', default: '1' },
    ],
    compute: ({ n, T, P }) => P === 0 ? 'Division by zero' : fmt((n * 0.082057 * T) / P),
  },
  { id: 'boyles-law', category: 'chemistry', name: "Boyle's Law",
    formula: 'P₁V₁ = P₂V₂', description: 'Solve for P₂',
    inputs: [
      { key: 'P1', symbol: 'P₁', label: 'P₁', default: '1' },
      { key: 'V1', symbol: 'V₁', label: 'V₁', default: '10' },
      { key: 'V2', symbol: 'V₂', label: 'V₂', default: '5' },
    ],
    compute: ({ P1, V1, V2 }) => V2 === 0 ? 'Division by zero' : fmt((P1 * V1) / V2),
  },
  { id: 'charles-law', category: 'chemistry', name: "Charles's Law",
    formula: 'V₁/T₁ = V₂/T₂', description: 'Solve for V₂',
    inputs: [
      { key: 'V1', symbol: 'V₁', label: 'V₁', default: '1' },
      { key: 'T1', symbol: 'T₁', label: 'T₁ (K)', default: '273' },
      { key: 'T2', symbol: 'T₂', label: 'T₂ (K)', default: '373' },
    ],
    compute: ({ V1, T1, T2 }) => T1 === 0 ? 'Division by zero' : fmt((V1 * T2) / T1),
  },
  { id: 'gay-lussac', category: 'chemistry', name: "Gay-Lussac's Law",
    formula: 'P₁/T₁ = P₂/T₂', description: 'Solve for P₂',
    inputs: [
      { key: 'P1', symbol: 'P₁', label: 'P₁', default: '1' },
      { key: 'T1', symbol: 'T₁', label: 'T₁ (K)', default: '273' },
      { key: 'T2', symbol: 'T₂', label: 'T₂ (K)', default: '373' },
    ],
    compute: ({ P1, T1, T2 }) => T1 === 0 ? 'Division by zero' : fmt((P1 * T2) / T1),
  },
  { id: 'combined-gas', category: 'chemistry', name: 'Combined Gas Law',
    formula: 'P₁V₁/T₁ = P₂V₂/T₂', description: 'Solve for P₂',
    inputs: [
      { key: 'P1', symbol: 'P₁', label: 'P₁', default: '1' },
      { key: 'V1', symbol: 'V₁', label: 'V₁', default: '1' },
      { key: 'T1', symbol: 'T₁', label: 'T₁ (K)', default: '273' },
      { key: 'V2', symbol: 'V₂', label: 'V₂', default: '2' },
      { key: 'T2', symbol: 'T₂', label: 'T₂ (K)', default: '546' },
    ],
    compute: ({ P1, V1, T1, V2, T2 }) => {
      if (V2 === 0 || T1 === 0) return 'Division by zero';
      return fmt((P1 * V1 * T2) / (T1 * V2));
    },
  },
  { id: 'daltons-partial', category: 'chemistry', name: "Dalton's Law",
    formula: 'P_total = P₁ + P₂ + P₃', description: 'Partial pressures',
    inputs: [
      { key: 'p1', symbol: 'P₁', label: 'P₁', default: '1' },
      { key: 'p2', symbol: 'P₂', label: 'P₂', default: '2' },
      { key: 'p3', symbol: 'P₃', label: 'P₃', default: '3' },
    ],
    compute: ({ p1, p2, p3 }) => fmt(p1 + p2 + p3),
  },
  { id: 'grahams-law', category: 'chemistry', name: "Graham's Law",
    formula: 'r₁/r₂ = √(M₂/M₁)', description: 'Effusion rate ratio',
    inputs: [
      { key: 'M1', symbol: 'M₁', label: 'Molar mass 1', default: '2' },
      { key: 'M2', symbol: 'M₂', label: 'Molar mass 2', default: '32' },
    ],
    compute: ({ M1, M2 }) => (M1 <= 0 || M2 <= 0) ? 'Invalid' : fmt(Math.sqrt(M2 / M1)),
  },

  // ─── Stoichiometry ────────────────────────────────────────────────────
  { id: 'percent-yield', category: 'chemistry', name: 'Percent Yield',
    formula: '% = (actual/theoretical)×100', description: 'Reaction efficiency',
    inputs: [
      { key: 'a', symbol: 'actual', label: 'Actual (g)', default: '15' },
      { key: 't', symbol: 'theory', label: 'Theoretical (g)', default: '20' },
    ],
    compute: ({ a, t }) => t === 0 ? 'Division by zero' : pct((a / t) * 100),
  },
  { id: 'percent-composition', category: 'chemistry', name: 'Percent Composition',
    formula: '% = (m_el/m_total)×100', description: 'Mass percent of element',
    inputs: [
      { key: 'me', symbol: 'm_el', label: 'Element mass (g)', default: '32' },
      { key: 'mt', symbol: 'm_total', label: 'Compound mass (g)', default: '98' },
    ],
    compute: ({ me, mt }) => mt === 0 ? 'Division by zero' : pct((me / mt) * 100),
  },
  { id: 'empirical-mass', category: 'chemistry', name: 'Empirical Mass',
    formula: 'M_emp = sum(atomic masses)', description: 'Sum of atomic masses',
    inputs: [
      { key: 'a', symbol: 'a', label: 'Element 1', default: '12' },
      { key: 'b', symbol: 'b', label: 'Element 2', default: '16' },
      { key: 'c', symbol: 'c', label: 'Element 3', default: '0' },
    ],
    compute: ({ a, b, c }) => fmt(a + b + c),
  },
  { id: 'percent-error', category: 'chemistry', name: 'Percent Error',
    formula: '% = |exp−true|/true × 100', description: 'Measurement accuracy',
    inputs: [
      { key: 'e', symbol: 'exp',  label: 'Experimental', default: '9.8' },
      { key: 't', symbol: 'true', label: 'True value',   default: '9.81' },
    ],
    compute: ({ e, t }) => t === 0 ? 'Division by zero' : pct(Math.abs(e - t) / Math.abs(t) * 100),
  },

  // ─── Acids & Bases ────────────────────────────────────────────────────
  { id: 'ph-from-h', category: 'chemistry', name: 'pH from [H⁺]',
    formula: 'pH = −log₁₀[H⁺]', description: 'pH',
    inputs: [{ key: 'H', symbol: '[H⁺]', label: 'Concentration (M)', default: '0.001' }],
    compute: ({ H }) => H <= 0 ? 'Must be > 0' : fmt(-Math.log10(H)),
  },
  { id: 'poh-from-oh', category: 'chemistry', name: 'pOH from [OH⁻]',
    formula: 'pOH = −log₁₀[OH⁻]', description: 'pOH',
    inputs: [{ key: 'OH', symbol: '[OH⁻]', label: 'Concentration (M)', default: '0.001' }],
    compute: ({ OH }) => OH <= 0 ? 'Must be > 0' : fmt(-Math.log10(OH)),
  },
  { id: 'ph-poh', category: 'chemistry', name: 'pH + pOH',
    formula: 'pH + pOH = 14', description: 'At 25°C',
    inputs: [{ key: 'poh', symbol: 'pOH', label: 'pOH', default: '4' }],
    compute: ({ poh }) => fmt(14 - poh),
  },
  { id: 'h-from-ph', category: 'chemistry', name: '[H⁺] from pH',
    formula: '[H⁺] = 10^(−pH)', description: 'Hydrogen concentration',
    inputs: [{ key: 'ph', symbol: 'pH', label: 'pH', default: '3' }],
    compute: ({ ph }) => fmt(Math.pow(10, -ph)),
  },
  { id: 'ka-from-pka', category: 'chemistry', name: 'Ka from pKa',
    formula: 'Ka = 10^(−pKa)', description: 'Acid constant',
    inputs: [{ key: 'pka', symbol: 'pKa', label: 'pKa', default: '4.76' }],
    compute: ({ pka }) => fmt(Math.pow(10, -pka)),
  },
  { id: 'pka-from-ka', category: 'chemistry', name: 'pKa from Ka',
    formula: 'pKa = −log₁₀(Ka)', description: 'pKa',
    inputs: [{ key: 'ka', symbol: 'Ka', label: 'Ka', default: '0.0000175' }],
    compute: ({ ka }) => ka <= 0 ? 'Must be > 0' : fmt(-Math.log10(ka)),
  },
  { id: 'kw-water', category: 'chemistry', name: 'Water Ion Product',
    formula: 'Kw = [H⁺][OH⁻] = 10⁻¹⁴', description: 'Solve for [OH⁻]',
    inputs: [{ key: 'H', symbol: '[H⁺]', label: 'H⁺ (M)', default: '0.0000001' }],
    compute: ({ H }) => H === 0 ? 'Division by zero' : fmt(1e-14 / H),
  },
  { id: 'henderson', category: 'chemistry', name: 'Henderson-Hasselbalch',
    formula: 'pH = pKa + log([A⁻]/[HA])', description: 'Buffer pH',
    inputs: [
      { key: 'pka', symbol: 'pKa', label: 'pKa', default: '4.76' },
      { key: 'a',   symbol: '[A⁻]', label: 'Base conc', default: '0.1' },
      { key: 'ha',  symbol: '[HA]', label: 'Acid conc', default: '0.1' },
    ],
    compute: ({ pka, a, ha }) => (a <= 0 || ha <= 0) ? 'Must be > 0' : fmt(pka + Math.log10(a / ha)),
  },

  // ─── Thermochemistry ──────────────────────────────────────────────────
  { id: 'heat-reaction', category: 'chemistry', name: 'Heat of Reaction',
    formula: 'Q = m·c·ΔT', description: 'Calorimetry',
    inputs: [
      { key: 'm',  symbol: 'm',  label: 'Mass (g)', default: '100' },
      { key: 'c',  symbol: 'c',  label: 'Specific heat (J/g·°C)', default: '4.18' },
      { key: 'dT', symbol: 'ΔT', label: 'ΔT (°C)', default: '10' },
    ],
    compute: ({ m, c, dT }) => fmt(m * c * dT),
  },
  { id: 'enthalpy-formation', category: 'chemistry', name: 'Enthalpy of Reaction',
    formula: 'ΔH = ΣΔH_products − ΣΔH_reactants', description: "Hess's law (2 terms)",
    inputs: [
      { key: 'hp', symbol: 'ΔH_p', label: 'Product enthalpy', default: '-394' },
      { key: 'hr', symbol: 'ΔH_r', label: 'Reactant enthalpy', default: '-200' },
    ],
    compute: ({ hp, hr }) => fmt(hp - hr),
  },
  { id: 'gibbs-free-energy', category: 'chemistry', name: 'Gibbs Free Energy',
    formula: 'ΔG = ΔH − T·ΔS', description: 'Spontaneity',
    inputs: [
      { key: 'dh', symbol: 'ΔH', label: 'Enthalpy (kJ/mol)', default: '-100' },
      { key: 'T',  symbol: 'T',  label: 'Temperature (K)', default: '298' },
      { key: 'ds', symbol: 'ΔS', label: 'Entropy (kJ/mol·K)', default: '0.05' },
    ],
    compute: ({ dh, T, ds }) => fmt(dh - T * ds),
  },
  { id: 'entropy-change', category: 'chemistry', name: 'Entropy Change',
    formula: 'ΔS = Q_rev/T', description: 'Reversible entropy',
    inputs: [
      { key: 'q', symbol: 'Q_rev', label: 'Heat (J)', default: '1000' },
      { key: 'T', symbol: 'T', label: 'Temperature (K)', default: '298' },
    ],
    compute: ({ q, T }) => T === 0 ? 'Division by zero' : fmt(q / T),
  },

  // ─── Kinetics ─────────────────────────────────────────────────────────
  { id: 'rate-law-simple', category: 'chemistry', name: 'Rate Law',
    formula: 'rate = k[A]^n', description: 'Reaction rate',
    inputs: [
      { key: 'k', symbol: 'k', label: 'Rate constant', default: '0.1' },
      { key: 'A', symbol: '[A]', label: 'Concentration', default: '1' },
      { key: 'n', symbol: 'n', label: 'Order', default: '1' },
    ],
    compute: ({ k, A, n }) => fmt(k * Math.pow(A, n)),
  },
  { id: 'arrhenius', category: 'chemistry', name: 'Arrhenius Equation',
    formula: 'k = A·exp(−Ea/RT)', description: 'Rate vs temperature',
    inputs: [
      { key: 'A',  symbol: 'A',  label: 'Pre-exponential', default: '1e13' },
      { key: 'Ea', symbol: 'Ea', label: 'Activation E (J/mol)', default: '50000' },
      { key: 'T',  symbol: 'T',  label: 'Temperature (K)', default: '300' },
    ],
    compute: ({ A, Ea, T }) => T === 0 ? 'Division by zero' : fmt(A * Math.exp(-Ea / (8.314 * T))),
  },
  { id: 'half-life-chem', category: 'chemistry', name: 'Radioactive Half-Life',
    formula: 'N = N₀·(½)^(t/t½)', description: 'Remaining amount',
    inputs: [
      { key: 'N0', symbol: 'N₀', label: 'Initial', default: '100' },
      { key: 't',  symbol: 't',  label: 'Time', default: '10' },
      { key: 'th', symbol: 't½', label: 'Half-life', default: '5' },
    ],
    compute: ({ N0, t, th }) => th === 0 ? 'Division by zero' : fmt(N0 * Math.pow(0.5, t / th)),
  },
  { id: 'decay-constant', category: 'chemistry', name: 'Decay Constant',
    formula: 'λ = ln(2)/t½', description: 'From half-life',
    inputs: [{ key: 'th', symbol: 't½', label: 'Half-life', default: '5' }],
    compute: ({ th }) => th === 0 ? 'Division by zero' : fmt(Math.LN2 / th),
  },

  // ─── Solutions ────────────────────────────────────────────────────────
  { id: 'raoults-law', category: 'chemistry', name: "Raoult's Law",
    formula: 'P_sol = x·P°', description: 'Vapor pressure',
    inputs: [
      { key: 'x',  symbol: 'x',  label: 'Mole fraction', default: '0.9' },
      { key: 'P0', symbol: 'P°', label: 'Pure vapor pressure', default: '100' },
    ],
    compute: ({ x, P0 }) => fmt(x * P0),
  },
  { id: 'freezing-depression', category: 'chemistry', name: 'Freezing Point Depression',
    formula: 'ΔT = Kf × m', description: 'Freezing point lowering',
    inputs: [
      { key: 'Kf', symbol: 'Kf', label: 'Kf', default: '1.86' },
      { key: 'm',  symbol: 'm',  label: 'Molality', default: '1' },
    ],
    compute: ({ Kf, m }) => fmt(Kf * m),
  },
  { id: 'boiling-elevation', category: 'chemistry', name: 'Boiling Point Elevation',
    formula: 'ΔT = Kb × m', description: 'Boiling point raising',
    inputs: [
      { key: 'Kb', symbol: 'Kb', label: 'Kb', default: '0.512' },
      { key: 'm',  symbol: 'm',  label: 'Molality', default: '1' },
    ],
    compute: ({ Kb, m }) => fmt(Kb * m),
  },
  { id: 'osmotic-pressure', category: 'chemistry', name: 'Osmotic Pressure',
    formula: 'π = MRT', description: 'Osmotic pressure',
    inputs: [
      { key: 'M', symbol: 'M', label: 'Molarity (M)', default: '0.1' },
      { key: 'T', symbol: 'T', label: 'Temperature (K)', default: '298' },
    ],
    compute: ({ M, T }) => fmt(M * 0.082057 * T),
  },

  // ─── Electrochemistry ─────────────────────────────────────────────────
  { id: 'nernst-equation', category: 'chemistry', name: 'Nernst Equation',
    formula: 'E = E° − (RT/nF)·ln(Q)', description: 'Cell potential',
    inputs: [
      { key: 'E0', symbol: 'E°', label: 'Standard potential (V)', default: '1.1' },
      { key: 'n',  symbol: 'n',  label: 'Electrons', default: '2' },
      { key: 'Q',  symbol: 'Q',  label: 'Reaction quotient', default: '1' },
      { key: 'T',  symbol: 'T',  label: 'Temperature (K)', default: '298' },
    ],
    compute: ({ E0, n, Q, T }) => (n === 0 || Q <= 0) ? 'Invalid' : fmt(E0 - (8.314 * T) / (n * 96485) * Math.log(Q)),
  },
  { id: 'faraday-mass', category: 'chemistry', name: 'Electrolysis Mass',
    formula: 'm = I·t·M/(n·F)', description: 'Mass deposited',
    inputs: [
      { key: 'I', symbol: 'I', label: 'Current (A)', default: '2' },
      { key: 't', symbol: 't', label: 'Time (s)', default: '3600' },
      { key: 'M', symbol: 'M', label: 'Molar mass (g/mol)', default: '63.5' },
      { key: 'n', symbol: 'n', label: 'Electrons', default: '2' },
    ],
    compute: ({ I, t, M, n }) => n === 0 ? 'Division by zero' : fmt((I * t * M) / (n * 96485)),
  },
  { id: 'cell-emf', category: 'chemistry', name: 'Cell EMF',
    formula: 'E°_cell = E°_cathode − E°_anode', description: 'Standard cell potential',
    inputs: [
      { key: 'Ec', symbol: 'E°_cat', label: 'Cathode E°', default: '0.34' },
      { key: 'Ea', symbol: 'E°_ano', label: 'Anode E°',   default: '-0.76' },
    ],
    compute: ({ Ec, Ea }) => fmt(Ec - Ea),
  },
];