// src/engine/formulas/electronics.js
// Electronics formulas — op-amps, transistors, diodes, filters, RF, PCB.

const fmt = (n) => {
  if (!Number.isFinite(n)) return 'Invalid';
  if (n === 0) return '0';
  const abs = Math.abs(n);
  if (abs < 1e-6 || abs >= 1e10) {
    return n.toExponential(4).replace(/\.?0+e/, 'e');
  }
  return Number(n.toPrecision(8)).toString();
};

const pct = (n) => `${fmt(n)} %`;

export const ELECTRONICS_FORMULAS = [
  // ─── Op-Amps ──────────────────────────────────────────────────────────
  { id: 'opamp-inverting', category: 'electronics', name: 'Op-Amp Inverting Gain',
    formula: 'A = −R_f / R_in', description: 'Inverting amplifier gain',
    inputs: [
      { key: 'Rf',  symbol: 'R_f',  label: 'Feedback R (Ω)', default: '10000' },
      { key: 'Rin', symbol: 'R_in', label: 'Input R (Ω)',    default: '1000' },
    ],
    compute: ({ Rf, Rin }) => Rin === 0 ? 'Division by zero' : fmt(-Rf / Rin),
  },
  { id: 'opamp-noninverting', category: 'electronics', name: 'Op-Amp Non-Inv Gain',
    formula: 'A = 1 + R_f / R_in', description: 'Non-inverting gain',
    inputs: [
      { key: 'Rf',  symbol: 'R_f',  label: 'Feedback R (Ω)', default: '10000' },
      { key: 'Rin', symbol: 'R_in', label: 'Input R (Ω)',    default: '1000' },
    ],
    compute: ({ Rf, Rin }) => Rin === 0 ? 'Division by zero' : fmt(1 + Rf / Rin),
  },
  { id: 'opamp-differential', category: 'electronics', name: 'Op-Amp Differential',
    formula: 'V_out = (R_f/R_in)(V₂ − V₁)', description: 'Differential amplifier',
    inputs: [
      { key: 'Rf',  symbol: 'R_f',  label: 'Feedback R (Ω)', default: '10000' },
      { key: 'Rin', symbol: 'R_in', label: 'Input R (Ω)',    default: '1000' },
      { key: 'V1',  symbol: 'V₁',   label: 'V₁ (V)', default: '1' },
      { key: 'V2',  symbol: 'V₂',   label: 'V₂ (V)', default: '2' },
    ],
    compute: ({ Rf, Rin, V1, V2 }) => Rin === 0 ? 'Division by zero' : fmt((Rf / Rin) * (V2 - V1)),
  },
  { id: 'opamp-integrator-tau', category: 'electronics', name: 'Op-Amp Integrator τ',
    formula: 'τ = R × C', description: 'Integrator time constant',
    inputs: [
      { key: 'R', symbol: 'R', label: 'Input R (Ω)', default: '10000' },
      { key: 'C', symbol: 'C', label: 'Feedback C (F)', default: '0.000001' },
    ],
    compute: ({ R, C }) => fmt(R * C),
  },
  { id: 'opamp-differentiator-tau', category: 'electronics', name: 'Op-Amp Differentiator τ',
    formula: 'τ = R × C', description: 'Differentiator time constant',
    inputs: [
      { key: 'R', symbol: 'R', label: 'Feedback R (Ω)', default: '10000' },
      { key: 'C', symbol: 'C', label: 'Input C (F)', default: '0.000001' },
    ],
    compute: ({ R, C }) => fmt(R * C),
  },
  { id: 'opamp-gbp-bw', category: 'electronics', name: 'Op-Amp Bandwidth',
    formula: 'BW = GBP / A_cl', description: 'Closed-loop bandwidth',
    inputs: [
      { key: 'gbp', symbol: 'GBP',  label: 'Gain-bandwidth (Hz)', default: '1000000' },
      { key: 'acl', symbol: 'A_cl', label: 'Closed-loop gain',    default: '10' },
    ],
    compute: ({ gbp, acl }) => acl === 0 ? 'Division by zero' : fmt(gbp / acl) + ' Hz',
  },
  { id: 'opamp-cmrr', category: 'electronics', name: 'Op-Amp CMRR',
    formula: 'CMRR = A_d / A_cm', description: 'Common-mode rejection ratio',
    inputs: [
      { key: 'Ad',  symbol: 'A_d',  label: 'Diff gain', default: '100000' },
      { key: 'Acm', symbol: 'A_cm', label: 'Common gain', default: '1' },
    ],
    compute: ({ Ad, Acm }) => Acm === 0 ? 'Division by zero' : fmt(Ad / Acm),
  },
  { id: 'opamp-slew-time', category: 'electronics', name: 'Op-Amp Slew Time',
    formula: 't = ΔV / SR', description: 'Time for voltage swing',
    inputs: [
      { key: 'dV', symbol: 'ΔV', label: 'Voltage swing (V)', default: '10' },
      { key: 'SR', symbol: 'SR', label: 'Slew rate (V/µs)',  default: '0.5' },
    ],
    compute: ({ dV, SR }) => SR === 0 ? 'Division by zero' : fmt(dV / SR) + ' µs',
  },

  // ─── Transistors ──────────────────────────────────────────────────────
  { id: 'bjt-beta', category: 'electronics', name: 'BJT β (hFE)',
    formula: 'β = I_C / I_B', description: 'Current gain',
    inputs: [
      { key: 'Ic', symbol: 'I_C', label: 'Collector I (A)', default: '0.1' },
      { key: 'Ib', symbol: 'I_B', label: 'Base I (A)',      default: '0.001' },
    ],
    compute: ({ Ic, Ib }) => Ib === 0 ? 'Division by zero' : fmt(Ic / Ib),
  },
  { id: 'bjt-ie', category: 'electronics', name: 'BJT Emitter Current',
    formula: 'I_E = I_C + I_B', description: 'Emitter current',
    inputs: [
      { key: 'Ic', symbol: 'I_C', label: 'Collector I (A)', default: '0.1' },
      { key: 'Ib', symbol: 'I_B', label: 'Base I (A)',      default: '0.001' },
    ],
    compute: ({ Ic, Ib }) => fmt(Ic + Ib),
  },
  { id: 'bjt-alpha', category: 'electronics', name: 'BJT α',
    formula: 'α = I_C / I_E', description: 'Common-base gain',
    inputs: [
      { key: 'Ic', symbol: 'I_C', label: 'Collector I (A)', default: '0.1' },
      { key: 'Ie', symbol: 'I_E', label: 'Emitter I (A)',   default: '0.101' },
    ],
    compute: ({ Ic, Ie }) => Ie === 0 ? 'Division by zero' : fmt(Ic / Ie),
  },
  { id: 'bjt-vce', category: 'electronics', name: 'BJT V_CE',
    formula: 'V_CE = V_CC − I_C·R_C', description: 'Collector-emitter voltage',
    inputs: [
      { key: 'Vcc', symbol: 'V_CC', label: 'Supply (V)', default: '12' },
      { key: 'Ic',  symbol: 'I_C',  label: 'Collector I (A)', default: '0.01' },
      { key: 'Rc',  symbol: 'R_C',  label: 'R_C (Ω)', default: '1000' },
    ],
    compute: ({ Vcc, Ic, Rc }) => fmt(Vcc - Ic * Rc),
  },
  { id: 'bjt-base-r', category: 'electronics', name: 'BJT Base Resistor',
    formula: 'R_B = (V_in − V_BE)/I_B', description: 'Base resistor',
    inputs: [
      { key: 'Vin', symbol: 'V_in', label: 'Input V', default: '5' },
      { key: 'Vbe', symbol: 'V_BE', label: 'V_BE',    default: '0.7' },
      { key: 'Ib',  symbol: 'I_B',  label: 'Base I (A)', default: '0.001' },
    ],
    compute: ({ Vin, Vbe, Ib }) => Ib === 0 ? 'Division by zero' : fmt((Vin - Vbe) / Ib),
  },
  { id: 'bjt-gm', category: 'electronics', name: 'BJT Transconductance',
    formula: 'g_m = I_C / V_T', description: 'Transconductance',
    inputs: [
      { key: 'Ic', symbol: 'I_C', label: 'Collector I (A)', default: '0.001' },
      { key: 'VT', symbol: 'V_T', label: 'Thermal V (V)',   default: '0.026' },
    ],
    compute: ({ Ic, VT }) => VT === 0 ? 'Division by zero' : fmt(Ic / VT),
  },
  { id: 'mosfet-id-sat', category: 'electronics', name: 'MOSFET I_D (saturation)',
    formula: 'I_D = ½·k·(V_GS−V_th)²', description: 'MOSFET drain current',
    inputs: [
      { key: 'k',   symbol: 'k',     label: 'k (A/V²)', default: '0.001' },
      { key: 'Vgs', symbol: 'V_GS',  label: 'V_GS (V)', default: '5' },
      { key: 'Vth', symbol: 'V_th',  label: 'V_th (V)', default: '2' },
    ],
    compute: ({ k, Vgs, Vth }) => {
      const vov = Vgs - Vth;
      return vov <= 0 ? 'Cutoff' : fmt(0.5 * k * vov * vov);
    },
  },

  // ─── Diodes ───────────────────────────────────────────────────────────
  { id: 'diode-shockley', category: 'electronics', name: 'Diode Current (Shockley)',
    formula: 'I = I_s·(e^(V/nV_T) − 1)', description: 'Diode current',
    inputs: [
      { key: 'Is', symbol: 'I_s', label: 'Saturation I (A)', default: '1e-12' },
      { key: 'V',  symbol: 'V',   label: 'Forward V (V)',    default: '0.7' },
      { key: 'n',  symbol: 'n',   label: 'Ideality',         default: '1' },
    ],
    compute: ({ Is, V, n }) => n === 0 ? 'Division by zero' : fmt(Is * (Math.exp(V / (n * 0.02585)) - 1)),
  },
  { id: 'diode-resistance', category: 'electronics', name: 'Diode Dynamic R',
    formula: 'r_d = n·V_T / I_D', description: 'Dynamic resistance',
    inputs: [
      { key: 'n',  symbol: 'n',   label: 'Ideality', default: '1' },
      { key: 'Id', symbol: 'I_D', label: 'Current (A)', default: '0.001' },
    ],
    compute: ({ n, Id }) => Id === 0 ? 'Division by zero' : fmt((n * 0.02585) / Id),
  },
  { id: 'zener-power', category: 'electronics', name: 'Zener Power',
    formula: 'P_z = V_z × I_z', description: 'Zener dissipation',
    inputs: [
      { key: 'Vz', symbol: 'V_z', label: 'Zener V', default: '5.1' },
      { key: 'Iz', symbol: 'I_z', label: 'Zener I (A)', default: '0.02' },
    ],
    compute: ({ Vz, Iz }) => fmt(Vz * Iz),
  },

  // ─── LED ──────────────────────────────────────────────────────────────
  { id: 'led-resistor', category: 'electronics', name: 'LED Resistor',
    formula: 'R = (V_s − V_LED) / I_LED', description: 'Series resistor',
    inputs: [
      { key: 'Vs', symbol: 'V_s', label: 'Supply (V)', default: '5' },
      { key: 'Vl', symbol: 'V_LED', label: 'Forward (V)', default: '2' },
      { key: 'Il', symbol: 'I_LED', label: 'Current (A)', default: '0.02' },
    ],
    compute: ({ Vs, Vl, Il }) => Il === 0 ? 'Division by zero' : fmt((Vs - Vl) / Il),
  },
  { id: 'led-power', category: 'electronics', name: 'LED Power',
    formula: 'P = V_f × I_f', description: 'LED dissipation',
    inputs: [
      { key: 'Vf', symbol: 'V_f', label: 'Forward (V)', default: '2' },
      { key: 'If', symbol: 'I_f', label: 'Current (A)', default: '0.02' },
    ],
    compute: ({ Vf, If }) => fmt(Vf * If),
  },

  // ─── Filters ──────────────────────────────────────────────────────────
  { id: 'rc-lowpass', category: 'electronics', name: 'RC Low-Pass f_c',
    formula: 'f_c = 1/(2πRC)', description: 'Low-pass cutoff',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '1000' },
      { key: 'C', symbol: 'C', label: 'C (F)', default: '0.000001' },
    ],
    compute: ({ R, C }) => (R <= 0 || C <= 0) ? 'Must be > 0' : fmt(1 / (2 * Math.PI * R * C)) + ' Hz',
  },
  { id: 'rl-highpass', category: 'electronics', name: 'RL High-Pass f_c',
    formula: 'f_c = R/(2πL)', description: 'High-pass cutoff',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '100' },
      { key: 'L', symbol: 'L', label: 'L (H)', default: '0.001' },
    ],
    compute: ({ R, L }) => L <= 0 ? 'Must be > 0' : fmt(R / (2 * Math.PI * L)) + ' Hz',
  },
  { id: 'rlc-resonance', category: 'electronics', name: 'RLC Resonance',
    formula: 'f = 1/(2π√(LC))', description: 'Resonant frequency',
    inputs: [
      { key: 'L', symbol: 'L', label: 'L (H)', default: '0.0001' },
      { key: 'C', symbol: 'C', label: 'C (F)', default: '0.0000001' },
    ],
    compute: ({ L, C }) => (L <= 0 || C <= 0) ? 'Must be > 0' : fmt(1 / (2 * Math.PI * Math.sqrt(L * C))) + ' Hz',
  },
  { id: 'rlc-bandwidth', category: 'electronics', name: 'RLC Bandwidth',
    formula: 'BW = f₀ / Q', description: 'Bandwidth from Q',
    inputs: [
      { key: 'f0', symbol: 'f₀', label: 'Resonance (Hz)', default: '1000' },
      { key: 'Q',  symbol: 'Q',  label: 'Q factor', default: '10' },
    ],
    compute: ({ f0, Q }) => Q === 0 ? 'Division by zero' : fmt(f0 / Q) + ' Hz',
  },
  { id: 'q-factor-series', category: 'electronics', name: 'Q Factor (Series RLC)',
    formula: 'Q = (1/R)·√(L/C)', description: 'Quality factor',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '10' },
      { key: 'L', symbol: 'L', label: 'L (H)', default: '0.001' },
      { key: 'C', symbol: 'C', label: 'C (F)', default: '0.0000001' },
    ],
    compute: ({ R, L, C }) => (R === 0 || C === 0) ? 'Division by zero' : fmt((1 / R) * Math.sqrt(L / C)),
  },

  // ─── dB & Gain ────────────────────────────────────────────────────────
  { id: 'db-from-voltage', category: 'electronics', name: 'dB from Voltage',
    formula: 'dB = 20·log₁₀(V_out/V_in)', description: 'Voltage gain in dB',
    inputs: [
      { key: 'Vout', symbol: 'V_out', label: 'Output V', default: '10' },
      { key: 'Vin',  symbol: 'V_in',  label: 'Input V',  default: '1' },
    ],
    compute: ({ Vout, Vin }) => (Vin <= 0 || Vout <= 0) ? 'Must be > 0' : `${fmt(20 * Math.log10(Vout / Vin))} dB`,
  },
  { id: 'db-from-power-e', category: 'electronics', name: 'dB from Power',
    formula: 'dB = 10·log₁₀(P_out/P_in)', description: 'Power gain in dB',
    inputs: [
      { key: 'Pout', symbol: 'P_out', label: 'Output P', default: '100' },
      { key: 'Pin',  symbol: 'P_in',  label: 'Input P',  default: '1' },
    ],
    compute: ({ Pout, Pin }) => (Pin <= 0 || Pout <= 0) ? 'Must be > 0' : `${fmt(10 * Math.log10(Pout / Pin))} dB`,
  },
  { id: 'db-to-voltage-ratio', category: 'electronics', name: 'dB to Voltage Ratio',
    formula: 'ratio = 10^(dB/20)', description: 'Voltage ratio from dB',
    inputs: [{ key: 'db', symbol: 'dB', label: 'Decibels', default: '20' }],
    compute: ({ db }) => fmt(Math.pow(10, db / 20)),
  },
  { id: 'db-to-power-ratio', category: 'electronics', name: 'dB to Power Ratio',
    formula: 'ratio = 10^(dB/10)', description: 'Power ratio from dB',
    inputs: [{ key: 'db', symbol: 'dB', label: 'Decibels', default: '10' }],
    compute: ({ db }) => fmt(Math.pow(10, db / 10)),
  },
  { id: 'cascade-gain', category: 'electronics', name: 'Cascade Power Gain',
    formula: 'G_total = G₁ × G₂', description: 'Two-stage gain',
    inputs: [
      { key: 'G1', symbol: 'G₁', label: 'Gain 1 (×)', default: '10' },
      { key: 'G2', symbol: 'G₂', label: 'Gain 2 (×)', default: '5' },
    ],
    compute: ({ G1, G2 }) => fmt(G1 * G2),
  },

  // ─── RF ───────────────────────────────────────────────────────────────
  { id: 'wavelength-from-freq', category: 'electronics', name: 'Wavelength from Frequency',
    formula: 'λ = c / f', description: 'EM wavelength',
    inputs: [{ key: 'f', symbol: 'f', label: 'Frequency (Hz)', default: '100000000' }],
    compute: ({ f }) => f === 0 ? 'Division by zero' : fmt(299792458 / f) + ' m',
  },
  { id: 'antenna-halfwave', category: 'electronics', name: 'Half-Wave Antenna',
    formula: 'L = 143 / f', description: 'Half-wave length (feet, f in MHz)',
    inputs: [{ key: 'f', symbol: 'f', label: 'Frequency (MHz)', default: '100' }],
    compute: ({ f }) => f === 0 ? 'Division by zero' : fmt(143 / f) + ' ft',
  },
  { id: 'dbm-to-mw', category: 'electronics', name: 'dBm to mW',
    formula: 'P = 10^(dBm/10)', description: 'Power from dBm',
    inputs: [{ key: 'dBm', symbol: 'dBm', label: 'dBm', default: '0' }],
    compute: ({ dBm }) => fmt(Math.pow(10, dBm / 10)) + ' mW',
  },
  { id: 'mw-to-dbm', category: 'electronics', name: 'mW to dBm',
    formula: 'dBm = 10·log₁₀(P)', description: 'dBm from power',
    inputs: [{ key: 'P', symbol: 'P', label: 'Power (mW)', default: '1' }],
    compute: ({ P }) => P <= 0 ? 'Must be > 0' : `${fmt(10 * Math.log10(P))} dBm`,
  },
  { id: 'cable-loss', category: 'electronics', name: 'Cable Loss',
    formula: 'L = L_per_m × length', description: 'Total cable loss',
    inputs: [
      { key: 'L', symbol: 'L_per_m', label: 'Loss (dB/m)', default: '0.2' },
      { key: 'm', symbol: 'length',  label: 'Length (m)',  default: '50' },
    ],
    compute: ({ L, m }) => fmt(L * m) + ' dB',
  },

  // ─── Signal & Communication ───────────────────────────────────────────
  { id: 'snr', category: 'electronics', name: 'Signal-to-Noise Ratio',
    formula: 'SNR = 20·log₁₀(V_s/V_n)', description: 'SNR in dB',
    inputs: [
      { key: 'Vs', symbol: 'V_s', label: 'Signal V', default: '1' },
      { key: 'Vn', symbol: 'V_n', label: 'Noise V',  default: '0.001' },
    ],
    compute: ({ Vs, Vn }) => Vn <= 0 ? 'Must be > 0' : `${fmt(20 * Math.log10(Vs / Vn))} dB`,
  },
  { id: 'noise-figure', category: 'electronics', name: 'Noise Figure',
    formula: 'NF = 10·log₁₀(F)', description: 'From noise factor',
    inputs: [{ key: 'F', symbol: 'F', label: 'Noise factor', default: '2' }],
    compute: ({ F }) => F <= 0 ? 'Must be > 0' : `${fmt(10 * Math.log10(F))} dB`,
  },
  { id: 'noise-temp', category: 'electronics', name: 'Noise Temperature',
    formula: 'T = 290 × (F − 1)', description: 'From noise factor',
    inputs: [{ key: 'F', symbol: 'F', label: 'Noise factor', default: '2' }],
    compute: ({ F }) => fmt(290 * (F - 1)) + ' K',
  },
  { id: 'thermal-noise-v', category: 'electronics', name: 'Thermal Noise Voltage',
    formula: 'V_n = √(4kTRB)', description: 'Johnson-Nyquist noise',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '1000' },
      { key: 'T', symbol: 'T', label: 'T (K)', default: '300' },
      { key: 'B', symbol: 'B', label: 'BW (Hz)', default: '20000' },
    ],
    compute: ({ R, T, B }) => fmt(Math.sqrt(4 * 1.380649e-23 * T * R * B)) + ' V',
  },
  { id: 'bit-rate-nyquist', category: 'electronics', name: 'Nyquist Bit Rate',
    formula: 'R = 2·B·log₂(M)', description: 'Data rate for M-ary signaling',
    inputs: [
      { key: 'B', symbol: 'B', label: 'BW (Hz)', default: '1000' },
      { key: 'M', symbol: 'M', label: 'Levels',  default: '4' },
    ],
    compute: ({ B, M }) => M <= 1 ? 'Invalid levels' : fmt(2 * B * Math.log2(M)) + ' bps',
  },
  { id: 'shannon-capacity', category: 'electronics', name: 'Shannon Capacity',
    formula: 'C = B·log₂(1 + SNR)', description: 'Channel capacity',
    inputs: [
      { key: 'B',   symbol: 'B',   label: 'BW (Hz)', default: '3000' },
      { key: 'SNR', symbol: 'SNR', label: 'SNR (linear)', default: '1000' },
    ],
    compute: ({ B, SNR }) => SNR < 0 ? 'Invalid SNR' : fmt(B * Math.log2(1 + SNR)) + ' bps',
  },
  { id: 'am-modulation-index', category: 'electronics', name: 'AM Modulation Index',
    formula: 'm = (A_max−A_min)/(A_max+A_min)', description: 'AM depth',
    inputs: [
      { key: 'Amax', symbol: 'A_max', label: 'Max amplitude', default: '2' },
      { key: 'Amin', symbol: 'A_min', label: 'Min amplitude', default: '0' },
    ],
    compute: ({ Amax, Amin }) => (Amax + Amin) === 0 ? 'Division by zero' : fmt((Amax - Amin) / (Amax + Amin)),
  },
  { id: 'fm-deviation', category: 'electronics', name: 'FM Deviation',
    formula: 'Δf = k × V_m', description: 'FM frequency deviation',
    inputs: [
      { key: 'k', symbol: 'k',   label: 'Sensitivity (Hz/V)', default: '5000' },
      { key: 'V', symbol: 'V_m', label: 'Mod amplitude (V)', default: '1' },
    ],
    compute: ({ k, V }) => fmt(k * V) + ' Hz',
  },

  // ─── Power Supplies ───────────────────────────────────────────────────
  { id: 'regulator-dissipation', category: 'electronics', name: 'Linear Reg Dissipation',
    formula: 'P = (V_in − V_out)·I', description: 'Regulator heat',
    inputs: [
      { key: 'Vin', symbol: 'V_in', label: 'Input (V)', default: '12' },
      { key: 'Vo',  symbol: 'V_out', label: 'Output (V)', default: '5' },
      { key: 'I',   symbol: 'I',   label: 'Current (A)', default: '1' },
    ],
    compute: ({ Vin, Vo, I }) => fmt((Vin - Vo) * I),
  },
  { id: 'regulator-efficiency', category: 'electronics', name: 'Linear Reg Efficiency',
    formula: 'η = V_out/V_in × 100', description: 'Efficiency',
    inputs: [
      { key: 'Vo', symbol: 'V_out', label: 'Output (V)', default: '5' },
      { key: 'Vi', symbol: 'V_in',  label: 'Input (V)',  default: '12' },
    ],
    compute: ({ Vo, Vi }) => Vi === 0 ? 'Division by zero' : pct((Vo / Vi) * 100),
  },
  { id: 'buck-output', category: 'electronics', name: 'Buck Converter V_out',
    formula: 'V_out = V_in × D', description: 'Ideal buck output',
    inputs: [
      { key: 'Vin', symbol: 'V_in', label: 'Input (V)', default: '12' },
      { key: 'D',   symbol: 'D',   label: 'Duty (0–1)', default: '0.5' },
    ],
    compute: ({ Vin, D }) => fmt(Vin * D),
  },
  { id: 'boost-output', category: 'electronics', name: 'Boost Converter V_out',
    formula: 'V_out = V_in/(1 − D)', description: 'Ideal boost output',
    inputs: [
      { key: 'Vin', symbol: 'V_in', label: 'Input (V)', default: '5' },
      { key: 'D',   symbol: 'D',   label: 'Duty (0–1)', default: '0.5' },
    ],
    compute: ({ Vin, D }) => D >= 1 ? 'Invalid duty' : fmt(Vin / (1 - D)),
  },
  { id: 'ps-ripple', category: 'electronics', name: 'PS Ripple Voltage',
    formula: 'V_ripple = I/(2fC)', description: 'Ripple voltage',
    inputs: [
      { key: 'I', symbol: 'I', label: 'Current (A)', default: '1' },
      { key: 'f', symbol: 'f', label: 'Freq (Hz)', default: '50' },
      { key: 'C', symbol: 'C', label: 'C (F)', default: '0.001' },
    ],
    compute: ({ I, f, C }) => (f === 0 || C === 0) ? 'Division by zero' : fmt(I / (2 * f * C)) + ' V',
  },

  // ─── Digital / Timing ─────────────────────────────────────────────────
  { id: 'pwm-duty', category: 'electronics', name: 'PWM Duty Cycle',
    formula: 'D = t_on/T × 100', description: 'Duty cycle',
    inputs: [
      { key: 'ton', symbol: 't_on', label: 'On time (s)', default: '0.001' },
      { key: 'T',   symbol: 'T',    label: 'Period (s)',  default: '0.004' },
    ],
    compute: ({ ton, T }) => T === 0 ? 'Division by zero' : pct((ton / T) * 100),
  },
  { id: 'pwm-avg-voltage', category: 'electronics', name: 'PWM Average Voltage',
    formula: 'V_avg = V_peak × D', description: 'PWM average output',
    inputs: [
      { key: 'Vp', symbol: 'V_peak', label: 'Peak (V)', default: '5' },
      { key: 'd',  symbol: 'D',      label: 'Duty (0–1)', default: '0.5' },
    ],
    compute: ({ Vp, d }) => fmt(Vp * d),
  },
  { id: 'rc-settling-5t', category: 'electronics', name: 'RC 5τ Settling',
    formula: 't = 5·R·C', description: 'Time to ~99% charge',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '1000' },
      { key: 'C', symbol: 'C', label: 'C (F)', default: '0.000001' },
    ],
    compute: ({ R, C }) => fmt(5 * R * C) + ' s',
  },
  { id: 'cap-charge-time', category: 'electronics', name: 'Capacitor Charge Time',
    formula: 't = −RC·ln(1 − V/V_s)', description: 'Time to reach V',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '1000' },
      { key: 'C', symbol: 'C', label: 'C (F)', default: '0.000001' },
      { key: 'V', symbol: 'V', label: 'Target V', default: '3' },
      { key: 'Vs', symbol: 'V_s', label: 'Supply V', default: '5' },
    ],
    compute: ({ R, C, V, Vs }) => {
      const ratio = V / Vs;
      if (ratio >= 1 || ratio <= 0) return 'Invalid ratio';
      return fmt(-R * C * Math.log(1 - ratio)) + ' s';
    },
  },

  // ─── Miscellaneous ────────────────────────────────────────────────────
  { id: 'electromagnet-force', category: 'electronics', name: 'Electromagnet Force',
    formula: 'F = B²·A / (2µ₀)', description: 'Force from B-field',
    inputs: [
      { key: 'B', symbol: 'B', label: 'B-field (T)', default: '1' },
      { key: 'A', symbol: 'A', label: 'Pole area (m²)', default: '0.01' },
    ],
    compute: ({ B, A }) => fmt((B * B * A) / (2 * 4 * Math.PI * 1e-7)),
  },
  { id: 'impedance-matching-l', category: 'electronics', name: 'Impedance Match (L)',
    formula: 'L = R/(2πf)', description: 'Match inductance',
    inputs: [
      { key: 'R', symbol: 'R', label: 'R (Ω)', default: '50' },
      { key: 'f', symbol: 'f', label: 'Frequency (Hz)', default: '1000000' },
    ],
    compute: ({ R, f }) => f === 0 ? 'Division by zero' : fmt(R / (2 * Math.PI * f)) + ' H',
  },
  { id: 'bit-period', category: 'electronics', name: 'Bit Period',
    formula: 'T = 1 / bit_rate', description: 'Time per bit',
    inputs: [{ key: 'rate', symbol: 'rate', label: 'Bit rate (bps)', default: '9600' }],
    compute: ({ rate }) => rate === 0 ? 'Division by zero' : fmt(1 / rate) + ' s',
  },
  { id: 'uart-baud-error', category: 'electronics', name: 'UART Baud Error',
    formula: '% error = ((actual − ideal)/ideal)×100', description: 'Baud rate error',
    inputs: [
      { key: 'a', symbol: 'actual', label: 'Actual baud', default: '9600' },
      { key: 'i', symbol: 'ideal',  label: 'Ideal baud',  default: '9600' },
    ],
    compute: ({ a, i }) => i === 0 ? 'Division by zero' : pct(((a - i) / i) * 100),
  },
];