// src/engine/formulas/physics.js
// Physics formulas — kinematics, dynamics, energy, waves, thermodynamics, modern physics.

const fmt = (n) => {
  if (!Number.isFinite(n)) return 'Invalid';
  if (n === 0) return '0';
  const abs = Math.abs(n);
  if (abs < 1e-6 || abs >= 1e10) {
    return n.toExponential(4).replace(/\.?0+e/, 'e');
  }
  return Number(n.toPrecision(8)).toString();
};

const pct = (n) => `${fmt(n)} %`;

export const PHYSICS_FORMULAS = [
  // ─── Kinematics ───────────────────────────────────────────────────────
  { id: 'speed', category: 'physics', name: 'Speed',
    formula: 'v = d / t', description: 'Average speed',
    inputs: [
      { key: 'd', symbol: 'd', label: 'Distance (m)', default: '100' },
      { key: 't', symbol: 't', label: 'Time (s)', default: '20' },
    ],
    compute: ({ d, t }) => t === 0 ? 'Division by zero' : fmt(d / t),
  },
  { id: 'acceleration', category: 'physics', name: 'Acceleration',
    formula: 'a = (v − u) / t', description: 'Acceleration',
    inputs: [
      { key: 'u', symbol: 'u', label: 'Initial v (m/s)', default: '0' },
      { key: 'v', symbol: 'v', label: 'Final v (m/s)',   default: '20' },
      { key: 't', symbol: 't', label: 'Time (s)', default: '5' },
    ],
    compute: ({ u, v, t }) => t === 0 ? 'Division by zero' : fmt((v - u) / t),
  },
  { id: 'eq-motion-1', category: 'physics', name: 'Motion Eq. 1',
    formula: 'v = u + a·t', description: 'Velocity after time t',
    inputs: [
      { key: 'u', symbol: 'u', label: 'Initial v', default: '0' },
      { key: 'a', symbol: 'a', label: 'Acceleration', default: '2' },
      { key: 't', symbol: 't', label: 'Time', default: '5' },
    ],
    compute: ({ u, a, t }) => fmt(u + a * t),
  },
  { id: 'eq-motion-2', category: 'physics', name: 'Motion Eq. 2',
    formula: 's = u·t + ½a·t²', description: 'Displacement',
    inputs: [
      { key: 'u', symbol: 'u', label: 'Initial v', default: '0' },
      { key: 'a', symbol: 'a', label: 'Acceleration', default: '2' },
      { key: 't', symbol: 't', label: 'Time', default: '5' },
    ],
    compute: ({ u, a, t }) => fmt(u * t + 0.5 * a * t * t),
  },
  { id: 'eq-motion-3', category: 'physics', name: 'Motion Eq. 3',
    formula: 'v² = u² + 2a·s', description: 'Velocity from displacement',
    inputs: [
      { key: 'u', symbol: 'u', label: 'Initial v', default: '0' },
      { key: 'a', symbol: 'a', label: 'Acceleration', default: '2' },
      { key: 's', symbol: 's', label: 'Displacement', default: '25' },
    ],
    compute: ({ u, a, s }) => {
      const v2 = u * u + 2 * a * s;
      return v2 < 0 ? 'Invalid' : fmt(Math.sqrt(v2));
    },
  },
  { id: 'average-velocity', category: 'physics', name: 'Average Velocity',
    formula: 'v = (u + vₑ) / 2', description: 'Average of initial and final',
    inputs: [
      { key: 'u',  symbol: 'u',  label: 'Initial v', default: '0' },
      { key: 've', symbol: 'vₑ', label: 'Final v',   default: '20' },
    ],
    compute: ({ u, ve }) => fmt((u + ve) / 2),
  },
  { id: 'projectile-range', category: 'physics', name: 'Projectile Range',
    formula: 'R = v²·sin(2θ)/g', description: 'Horizontal range',
    inputs: [
      { key: 'v', symbol: 'v', label: 'Speed (m/s)', default: '20' },
      { key: 'theta', symbol: 'θ', label: 'Angle (°)', default: '45' },
    ],
    compute: ({ v, theta }) => fmt((v * v * Math.sin(2 * theta * Math.PI / 180)) / 9.81),
  },
  { id: 'projectile-max-height', category: 'physics', name: 'Max Height',
    formula: 'h = v²·sin²(θ)/(2g)', description: 'Projectile max height',
    inputs: [
      { key: 'v', symbol: 'v', label: 'Speed (m/s)', default: '20' },
      { key: 'theta', symbol: 'θ', label: 'Angle (°)', default: '45' },
    ],
    compute: ({ v, theta }) => {
      const s = Math.sin(theta * Math.PI / 180);
      return fmt((v * v * s * s) / (2 * 9.81));
    },
  },
  { id: 'projectile-time', category: 'physics', name: 'Time of Flight',
    formula: 't = 2v·sin(θ)/g', description: 'Projectile time of flight',
    inputs: [
      { key: 'v', symbol: 'v', label: 'Speed (m/s)', default: '20' },
      { key: 'theta', symbol: 'θ', label: 'Angle (°)', default: '45' },
    ],
    compute: ({ v, theta }) => fmt((2 * v * Math.sin(theta * Math.PI / 180)) / 9.81),
  },

  // ─── Force & Dynamics ─────────────────────────────────────────────────
  { id: 'force', category: 'physics', name: "Newton's 2nd Law",
    formula: 'F = m × a', description: 'Force from mass and acceleration',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '10' },
      { key: 'a', symbol: 'a', label: 'Acceleration (m/s²)', default: '2' },
    ],
    compute: ({ m, a }) => fmt(m * a),
  },
  { id: 'weight', category: 'physics', name: 'Weight',
    formula: 'W = m × g', description: 'Weight (g = 9.81)',
    inputs: [{ key: 'm', symbol: 'm', label: 'Mass (kg)', default: '10' }],
    compute: ({ m }) => fmt(m * 9.81),
  },
  { id: 'friction-force', category: 'physics', name: 'Friction Force',
    formula: 'f = μ × N', description: 'Friction force',
    inputs: [
      { key: 'mu', symbol: 'μ', label: 'Coefficient', default: '0.3' },
      { key: 'N',  symbol: 'N', label: 'Normal force (N)', default: '100' },
    ],
    compute: ({ mu, N }) => fmt(mu * N),
  },
  { id: 'centripetal-force', category: 'physics', name: 'Centripetal Force',
    formula: 'F = mv²/r', description: 'Circular motion force',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '1' },
      { key: 'v', symbol: 'v', label: 'Velocity (m/s)', default: '10' },
      { key: 'r', symbol: 'r', label: 'Radius (m)', default: '5' },
    ],
    compute: ({ m, v, r }) => r === 0 ? 'Division by zero' : fmt(m * v * v / r),
  },
  { id: 'hookes-law', category: 'physics', name: "Hooke's Law",
    formula: 'F = k × x', description: 'Spring force',
    inputs: [
      { key: 'k', symbol: 'k', label: 'Spring constant (N/m)', default: '100' },
      { key: 'x', symbol: 'x', label: 'Extension (m)', default: '0.1' },
    ],
    compute: ({ k, x }) => fmt(k * x),
  },
  { id: 'gravitation', category: 'physics', name: 'Universal Gravitation',
    formula: 'F = G·m₁·m₂/r²', description: 'Gravitational force',
    inputs: [
      { key: 'm1', symbol: 'm₁', label: 'Mass 1 (kg)', default: '5.97e24' },
      { key: 'm2', symbol: 'm₂', label: 'Mass 2 (kg)', default: '7.35e22' },
      { key: 'r',  symbol: 'r',  label: 'Distance (m)', default: '3.84e8' },
    ],
    compute: ({ m1, m2, r }) => r === 0 ? 'Division by zero' : fmt((6.67430e-11 * m1 * m2) / (r * r)),
  },

  // ─── Work, Energy, Power ──────────────────────────────────────────────
  { id: 'work', category: 'physics', name: 'Work',
    formula: 'W = F × d', description: 'Work from force and distance',
    inputs: [
      { key: 'F', symbol: 'F', label: 'Force (N)', default: '50' },
      { key: 'd', symbol: 'd', label: 'Distance (m)', default: '10' },
    ],
    compute: ({ F, d }) => fmt(F * d),
  },
  { id: 'work-angle', category: 'physics', name: 'Work (at angle)',
    formula: 'W = F·d·cos(θ)', description: 'Work at angle',
    inputs: [
      { key: 'F', symbol: 'F', label: 'Force (N)', default: '50' },
      { key: 'd', symbol: 'd', label: 'Distance (m)', default: '10' },
      { key: 'theta', symbol: 'θ', label: 'Angle (°)', default: '30' },
    ],
    compute: ({ F, d, theta }) => fmt(F * d * Math.cos(theta * Math.PI / 180)),
  },
  { id: 'power', category: 'physics', name: 'Power',
    formula: 'P = W / t', description: 'Power from work and time',
    inputs: [
      { key: 'W', symbol: 'W', label: 'Work (J)', default: '500' },
      { key: 't', symbol: 't', label: 'Time (s)', default: '10' },
    ],
    compute: ({ W, t }) => t === 0 ? 'Division by zero' : fmt(W / t),
  },
  { id: 'kinetic-energy', category: 'physics', name: 'Kinetic Energy',
    formula: 'Ek = ½mv²', description: 'Kinetic energy',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '5' },
      { key: 'v', symbol: 'v', label: 'Velocity (m/s)', default: '10' },
    ],
    compute: ({ m, v }) => fmt(0.5 * m * v * v),
  },
  { id: 'potential-energy', category: 'physics', name: 'Potential Energy',
    formula: 'Ep = mgh', description: 'Gravitational PE',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '10' },
      { key: 'h', symbol: 'h', label: 'Height (m)', default: '5' },
    ],
    compute: ({ m, h }) => fmt(m * 9.81 * h),
  },
  { id: 'mechanical-energy', category: 'physics', name: 'Mechanical Energy',
    formula: 'E = Ek + Ep', description: 'Total mechanical energy',
    inputs: [
      { key: 'Ek', symbol: 'Ek', label: 'Kinetic (J)', default: '100' },
      { key: 'Ep', symbol: 'Ep', label: 'Potential (J)', default: '50' },
    ],
    compute: ({ Ek, Ep }) => fmt(Ek + Ep),
  },
  { id: 'spring-energy', category: 'physics', name: 'Spring Potential Energy',
    formula: 'Ep = ½kx²', description: 'Energy in a spring',
    inputs: [
      { key: 'k', symbol: 'k', label: 'Spring constant (N/m)', default: '100' },
      { key: 'x', symbol: 'x', label: 'Extension (m)', default: '0.1' },
    ],
    compute: ({ k, x }) => fmt(0.5 * k * x * x),
  },
  { id: 'efficiency', category: 'physics', name: 'Efficiency',
    formula: 'η = (output/input) × 100', description: 'Energy efficiency',
    inputs: [
      { key: 'Po', symbol: 'P_out', label: 'Output', default: '80' },
      { key: 'Pi', symbol: 'P_in',  label: 'Input',  default: '100' },
    ],
    compute: ({ Po, Pi }) => Pi === 0 ? 'Division by zero' : pct((Po / Pi) * 100),
  },

  // ─── Momentum & Collisions ────────────────────────────────────────────
  { id: 'momentum', category: 'physics', name: 'Momentum',
    formula: 'p = m × v', description: 'Linear momentum',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '5' },
      { key: 'v', symbol: 'v', label: 'Velocity (m/s)', default: '8' },
    ],
    compute: ({ m, v }) => fmt(m * v),
  },
  { id: 'impulse', category: 'physics', name: 'Impulse',
    formula: 'J = F × Δt', description: 'Impulse',
    inputs: [
      { key: 'F', symbol: 'F', label: 'Force (N)', default: '50' },
      { key: 't', symbol: 'Δt', label: 'Time (s)', default: '0.5' },
    ],
    compute: ({ F, t }) => fmt(F * t),
  },
  { id: 'elastic-collision-v1', category: 'physics', name: 'Elastic v₁',
    formula: 'v₁ = ((m₁−m₂)u₁ + 2m₂u₂)/(m₁+m₂)', description: 'Elastic collision final v₁',
    inputs: [
      { key: 'm1', symbol: 'm₁', label: 'Mass 1 (kg)', default: '1' },
      { key: 'm2', symbol: 'm₂', label: 'Mass 2 (kg)', default: '1' },
      { key: 'u1', symbol: 'u₁', label: 'Initial v₁', default: '5' },
      { key: 'u2', symbol: 'u₂', label: 'Initial v₂', default: '0' },
    ],
    compute: ({ m1, m2, u1, u2 }) => {
      const m = m1 + m2;
      return m === 0 ? 'Division by zero' : fmt(((m1 - m2) * u1 + 2 * m2 * u2) / m);
    },
  },

  // ─── Fluid Mechanics ──────────────────────────────────────────────────
  { id: 'density', category: 'physics', name: 'Density',
    formula: 'ρ = m / V', description: 'Density',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '10' },
      { key: 'V', symbol: 'V', label: 'Volume (m³)', default: '2' },
    ],
    compute: ({ m, V }) => V === 0 ? 'Division by zero' : fmt(m / V),
  },
  { id: 'pressure', category: 'physics', name: 'Pressure',
    formula: 'P = F / A', description: 'Pressure',
    inputs: [
      { key: 'F', symbol: 'F', label: 'Force (N)', default: '100' },
      { key: 'A', symbol: 'A', label: 'Area (m²)', default: '2' },
    ],
    compute: ({ F, A }) => A === 0 ? 'Division by zero' : fmt(F / A),
  },
  { id: 'hydrostatic-p', category: 'physics', name: 'Hydrostatic Pressure',
    formula: 'P = ρgh', description: 'Pressure at depth',
    inputs: [
      { key: 'rho', symbol: 'ρ', label: 'Density (kg/m³)', default: '1000' },
      { key: 'h',   symbol: 'h', label: 'Depth (m)', default: '10' },
    ],
    compute: ({ rho, h }) => fmt(rho * 9.81 * h),
  },
  { id: 'buoyancy', category: 'physics', name: 'Buoyant Force',
    formula: 'F = ρ·V·g', description: 'Buoyancy (Archimedes)',
    inputs: [
      { key: 'rho', symbol: 'ρ', label: 'Fluid density (kg/m³)', default: '1000' },
      { key: 'V',   symbol: 'V', label: 'Displaced volume (m³)', default: '0.01' },
    ],
    compute: ({ rho, V }) => fmt(rho * V * 9.81),
  },
  { id: 'flow-rate', category: 'physics', name: 'Volume Flow Rate',
    formula: 'Q = A × v', description: 'Flow rate',
    inputs: [
      { key: 'A', symbol: 'A', label: 'Area (m²)', default: '0.01' },
      { key: 'v', symbol: 'v', label: 'Velocity (m/s)', default: '2' },
    ],
    compute: ({ A, v }) => fmt(A * v),
  },
  { id: 'continuity', category: 'physics', name: 'Continuity Equation',
    formula: 'A₁v₁ = A₂v₂', description: 'Solve for v₂',
    inputs: [
      { key: 'A1', symbol: 'A₁', label: 'Area 1 (m²)', default: '0.1' },
      { key: 'v1', symbol: 'v₁', label: 'Velocity 1 (m/s)', default: '2' },
      { key: 'A2', symbol: 'A₂', label: 'Area 2 (m²)', default: '0.05' },
    ],
    compute: ({ A1, v1, A2 }) => A2 === 0 ? 'Division by zero' : fmt((A1 * v1) / A2),
  },
  { id: 'bernoulli', category: 'physics', name: "Bernoulli's Equation",
    formula: 'P + ½ρv² + ρgh = constant', description: 'Solve for P₂',
    inputs: [
      { key: 'P1', symbol: 'P₁', label: 'Pressure 1 (Pa)', default: '101325' },
      { key: 'rho', symbol: 'ρ', label: 'Density (kg/m³)', default: '1000' },
      { key: 'v1', symbol: 'v₁', label: 'Velocity 1 (m/s)', default: '1' },
      { key: 'v2', symbol: 'v₂', label: 'Velocity 2 (m/s)', default: '3' },
      { key: 'h1', symbol: 'h₁', label: 'Height 1 (m)', default: '0' },
      { key: 'h2', symbol: 'h₂', label: 'Height 2 (m)', default: '0' },
    ],
    compute: ({ P1, rho, v1, v2, h1, h2 }) => {
      const p2 = P1 + 0.5 * rho * (v1 * v1 - v2 * v2) + rho * 9.81 * (h1 - h2);
      return fmt(p2);
    },
  },

  // ─── Waves & Sound ────────────────────────────────────────────────────
  { id: 'wave-speed', category: 'physics', name: 'Wave Speed',
    formula: 'v = f × λ', description: 'Wave speed',
    inputs: [
      { key: 'f', symbol: 'f', label: 'Frequency (Hz)', default: '50' },
      { key: 'l', symbol: 'λ', label: 'Wavelength (m)', default: '2' },
    ],
    compute: ({ f, l }) => fmt(f * l),
  },
  { id: 'wave-period', category: 'physics', name: 'Wave Period',
    formula: 'T = 1 / f', description: 'Period from frequency',
    inputs: [{ key: 'f', symbol: 'f', label: 'Frequency (Hz)', default: '50' }],
    compute: ({ f }) => f === 0 ? 'Division by zero' : fmt(1 / f),
  },
  { id: 'sound-distance', category: 'physics', name: 'Sound Distance',
    formula: 'd = v × t', description: 'Distance from sound',
    inputs: [
      { key: 'v', symbol: 'v', label: 'Speed (m/s)', default: '343' },
      { key: 't', symbol: 't', label: 'Time (s)', default: '2' },
    ],
    compute: ({ v, t }) => fmt(v * t),
  },
  { id: 'doppler', category: 'physics', name: 'Doppler Effect',
    formula: 'f_obs = f_s·v/(v − v_s)', description: 'Observed frequency',
    inputs: [
      { key: 'fs', symbol: 'f_s', label: 'Source freq (Hz)', default: '500' },
      { key: 'v',  symbol: 'v',   label: 'Speed of sound (m/s)', default: '343' },
      { key: 'vs', symbol: 'v_s', label: 'Source speed (m/s)', default: '30' },
    ],
    compute: ({ fs, v, vs }) => v - vs === 0 ? 'Source at speed of sound' : fmt((fs * v) / (v - vs)),
  },
  { id: 'beat-frequency', category: 'physics', name: 'Beat Frequency',
    formula: 'f_beat = |f₁ − f₂|', description: 'Beat frequency',
    inputs: [
      { key: 'f1', symbol: 'f₁', label: 'Frequency 1 (Hz)', default: '440' },
      { key: 'f2', symbol: 'f₂', label: 'Frequency 2 (Hz)', default: '444' },
    ],
    compute: ({ f1, f2 }) => fmt(Math.abs(f1 - f2)),
  },

  // ─── Thermodynamics ───────────────────────────────────────────────────
  { id: 'heat-energy', category: 'physics', name: 'Heat Energy',
    formula: 'Q = m·c·ΔT', description: 'Heat for temperature change',
    inputs: [
      { key: 'm',  symbol: 'm',  label: 'Mass (kg)', default: '2' },
      { key: 'c',  symbol: 'c',  label: 'Specific heat (J/kg·K)', default: '4186' },
      { key: 'dT', symbol: 'ΔT', label: 'Temp change (K)', default: '10' },
    ],
    compute: ({ m, c, dT }) => fmt(m * c * dT),
  },
  { id: 'latent-heat', category: 'physics', name: 'Latent Heat',
    formula: 'Q = m·L', description: 'Heat for phase change',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '1' },
      { key: 'L', symbol: 'L', label: 'Latent heat (J/kg)', default: '334000' },
    ],
    compute: ({ m, L }) => fmt(m * L),
  },
  { id: 'ideal-gas-p', category: 'physics', name: 'Ideal Gas (P)',
    formula: 'P = nRT/V', description: 'Gas pressure',
    inputs: [
      { key: 'n', symbol: 'n', label: 'Moles', default: '1' },
      { key: 'T', symbol: 'T', label: 'Temperature (K)', default: '300' },
      { key: 'V', symbol: 'V', label: 'Volume (m³)', default: '0.0224' },
    ],
    compute: ({ n, T, V }) => V === 0 ? 'Division by zero' : fmt((n * 8.314 * T) / V),
  },
  { id: 'thermal-expansion', category: 'physics', name: 'Thermal Expansion',
    formula: 'ΔL = L₀·α·ΔT', description: 'Linear thermal expansion',
    inputs: [
      { key: 'L0', symbol: 'L₀', label: 'Length (m)', default: '1' },
      { key: 'a',  symbol: 'α',  label: 'Expansion coeff (1/K)', default: '0.000012' },
      { key: 'dT', symbol: 'ΔT', label: 'Temp change (K)', default: '50' },
    ],
    compute: ({ L0, a, dT }) => fmt(L0 * a * dT),
  },
  { id: 'carnot', category: 'physics', name: 'Carnot Efficiency',
    formula: 'η = 1 − T_cold/T_hot', description: 'Max heat engine efficiency',
    inputs: [
      { key: 'Tc', symbol: 'T_cold', label: 'Cold temp (K)', default: '300' },
      { key: 'Th', symbol: 'T_hot',  label: 'Hot temp (K)',  default: '500' },
    ],
    compute: ({ Tc, Th }) => Th === 0 ? 'Division by zero' : pct((1 - Tc / Th) * 100),
  },

  // ─── Electricity (Physics) ────────────────────────────────────────────
  { id: 'ohm-physics', category: 'physics', name: "Ohm's Law",
    formula: 'V = I × R', description: 'Voltage',
    inputs: [
      { key: 'I', symbol: 'I', label: 'Current (A)', default: '2' },
      { key: 'R', symbol: 'R', label: 'Resistance (Ω)', default: '10' },
    ],
    compute: ({ I, R }) => fmt(I * R),
  },
  { id: 'electric-power', category: 'physics', name: 'Electric Power',
    formula: 'P = V × I', description: 'Electrical power',
    inputs: [
      { key: 'V', symbol: 'V', label: 'Voltage (V)', default: '12' },
      { key: 'I', symbol: 'I', label: 'Current (A)', default: '2' },
    ],
    compute: ({ V, I }) => fmt(V * I),
  },
  { id: 'coulomb-force', category: 'physics', name: "Coulomb's Law",
    formula: 'F = k·q₁·q₂/r²', description: 'Force between charges',
    inputs: [
      { key: 'q1', symbol: 'q₁', label: 'Charge 1 (C)', default: '0.000001' },
      { key: 'q2', symbol: 'q₂', label: 'Charge 2 (C)', default: '0.000001' },
      { key: 'r',  symbol: 'r',  label: 'Distance (m)', default: '1' },
    ],
    compute: ({ q1, q2, r }) => r === 0 ? 'Division by zero' : fmt((8.9875517923e9 * q1 * q2) / (r * r)),
  },
  { id: 'electric-field', category: 'physics', name: 'Electric Field',
    formula: 'E = F / q', description: 'Field from force and charge',
    inputs: [
      { key: 'F', symbol: 'F', label: 'Force (N)', default: '10' },
      { key: 'q', symbol: 'q', label: 'Charge (C)', default: '2' },
    ],
    compute: ({ F, q }) => q === 0 ? 'Division by zero' : fmt(F / q),
  },
  { id: 'magnetic-force', category: 'physics', name: 'Magnetic Force',
    formula: 'F = q·v·B·sin(θ)', description: 'Force on moving charge',
    inputs: [
      { key: 'q', symbol: 'q', label: 'Charge (C)', default: '0.001' },
      { key: 'v', symbol: 'v', label: 'Velocity (m/s)', default: '100' },
      { key: 'B', symbol: 'B', label: 'B-field (T)', default: '0.5' },
      { key: 'theta', symbol: 'θ', label: 'Angle (°)', default: '90' },
    ],
    compute: ({ q, v, B, theta }) => fmt(q * v * B * Math.sin(theta * Math.PI / 180)),
  },

  // ─── Astronomy ────────────────────────────────────────────────────────
  { id: 'orbital-speed', category: 'physics', name: 'Orbital Speed',
    formula: 'v = √(GM/r)', description: 'Circular orbit speed',
    inputs: [
      { key: 'M', symbol: 'M', label: 'Central mass (kg)', default: '5.97e24' },
      { key: 'r', symbol: 'r', label: 'Orbit radius (m)', default: '6.78e6' },
    ],
    compute: ({ M, r }) => r === 0 ? 'Division by zero' : fmt(Math.sqrt((6.67430e-11 * M) / r)),
  },
  { id: 'escape-velocity', category: 'physics', name: 'Escape Velocity',
    formula: 'v = √(2GM/r)', description: 'Escape velocity',
    inputs: [
      { key: 'M', symbol: 'M', label: 'Mass (kg)', default: '5.97e24' },
      { key: 'r', symbol: 'r', label: 'Radius (m)', default: '6.37e6' },
    ],
    compute: ({ M, r }) => r === 0 ? 'Division by zero' : fmt(Math.sqrt((2 * 6.67430e-11 * M) / r)),
  },
  { id: 'kepler-third', category: 'physics', name: "Kepler's 3rd Law",
    formula: 'T² = 4π²a³/(GM)', description: 'Orbital period',
    inputs: [
      { key: 'a', symbol: 'a', label: 'Semi-major axis (m)', default: '1.5e11' },
      { key: 'M', symbol: 'M', label: 'Central mass (kg)', default: '1.989e30' },
    ],
    compute: ({ a, M }) => M === 0 ? 'Division by zero' : fmt(2 * Math.PI * Math.sqrt((a * a * a) / (6.67430e-11 * M))),
  },

  // ─── Rotation ─────────────────────────────────────────────────────────
  { id: 'torque', category: 'physics', name: 'Torque',
    formula: 'τ = F·r·sin(θ)', description: 'Torque',
    inputs: [
      { key: 'F', symbol: 'F', label: 'Force (N)', default: '100' },
      { key: 'r', symbol: 'r', label: 'Lever arm (m)', default: '0.5' },
      { key: 'theta', symbol: 'θ', label: 'Angle (°)', default: '90' },
    ],
    compute: ({ F, r, theta }) => fmt(F * r * Math.sin(theta * Math.PI / 180)),
  },
  { id: 'angular-velocity', category: 'physics', name: 'Angular Velocity',
    formula: 'ω = θ / t', description: 'Angular velocity',
    inputs: [
      { key: 'theta', symbol: 'θ', label: 'Angle (rad)', default: '6.28' },
      { key: 't',     symbol: 't', label: 'Time (s)', default: '2' },
    ],
    compute: ({ theta, t }) => t === 0 ? 'Division by zero' : fmt(theta / t),
  },
  { id: 'rotational-ke', category: 'physics', name: 'Rotational KE',
    formula: 'Ek = ½Iω²', description: 'Rotational kinetic energy',
    inputs: [
      { key: 'I', symbol: 'I', label: 'Moment of inertia', default: '1' },
      { key: 'w', symbol: 'ω', label: 'Angular velocity', default: '10' },
    ],
    compute: ({ I, w }) => fmt(0.5 * I * w * w),
  },

  // ─── Modern Physics ───────────────────────────────────────────────────
  { id: 'energy-mass', category: 'physics', name: 'Mass-Energy Equivalence',
    formula: 'E = m·c²', description: 'Einstein E=mc²',
    inputs: [{ key: 'm', symbol: 'm', label: 'Mass (kg)', default: '1' }],
    compute: ({ m }) => fmt(m * Math.pow(299792458, 2)),
  },
  { id: 'photon-energy', category: 'physics', name: 'Photon Energy',
    formula: 'E = h·f', description: 'Photon energy',
    inputs: [{ key: 'f', symbol: 'f', label: 'Frequency (Hz)', default: '5e14' }],
    compute: ({ f }) => fmt(6.62607015e-34 * f),
  },
  { id: 'de-broglie', category: 'physics', name: 'de Broglie Wavelength',
    formula: 'λ = h/(m·v)', description: 'Matter wavelength',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '9.11e-31' },
      { key: 'v', symbol: 'v', label: 'Velocity (m/s)', default: '1e6' },
    ],
    compute: ({ m, v }) => (m * v) === 0 ? 'Division by zero' : fmt(6.62607015e-34 / (m * v)),
  },
  { id: 'half-life', category: 'physics', name: 'Radioactive Decay',
    formula: 'N = N₀·(½)^(t/t½)', description: 'Remaining after time t',
    inputs: [
      { key: 'N0', symbol: 'N₀', label: 'Initial', default: '1000' },
      { key: 't',  symbol: 't',  label: 'Time', default: '10' },
      { key: 'th', symbol: 't½', label: 'Half-life', default: '5' },
    ],
    compute: ({ N0, t, th }) => th === 0 ? 'Division by zero' : fmt(N0 * Math.pow(0.5, t / th)),
  },

  // ─── Misc ─────────────────────────────────────────────────────────────
  { id: 'ph-physics', category: 'physics', name: 'pH',
    formula: 'pH = −log₁₀[H⁺]', description: 'pH from concentration',
    inputs: [{ key: 'H', symbol: '[H⁺]', label: 'Concentration (M)', default: '0.001' }],
    compute: ({ H }) => H <= 0 ? 'Must be > 0' : fmt(-Math.log10(H)),
  },
  { id: 'specific-heat-q', category: 'physics', name: 'Molar Heat Capacity',
    formula: 'Q = n·C·ΔT', description: 'Heat for n moles',
    inputs: [
      { key: 'n',  symbol: 'n',  label: 'Moles', default: '1' },
      { key: 'C',  symbol: 'C',  label: 'Molar heat (J/mol·K)', default: '30' },
      { key: 'dT', symbol: 'ΔT', label: 'Temp change (K)', default: '10' },
    ],
    compute: ({ n, C, dT }) => fmt(n * C * dT),
  },
  { id: 'moment-of-inertia', category: 'physics', name: 'Moment of Inertia (Point)',
    formula: 'I = m·r²', description: 'Point mass moment of inertia',
    inputs: [
      { key: 'm', symbol: 'm', label: 'Mass (kg)', default: '2' },
      { key: 'r', symbol: 'r', label: 'Radius (m)', default: '1' },
    ],
    compute: ({ m, r }) => fmt(m * r * r),
  },
];